import type { ICatCard } from '@/components/card/cat/CatCard';
import CatCard from '@/components/card/cat/CatCard';
import Head from 'next/head';

const base: ICatCard = {
  tag: 'Felines',
  title: `What's new in Cats`,
  body: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi perferendis molestiae non nemo doloribus. Doloremque, nihil! At ea atque quidem!',
  author: 'Alex',
  time: '2h ago',
};

export default function Home() {
  return (
    <div className='flex min-h-screen flex-col items-center justify-center py-2'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='p-4'>
        <h1 className='mb-4 text-center text-7xl font-bold'>
          Welcome to{' '}
          <a
            href='https://nextjs.org'
            className='text-blue-500 hover:underline'
          >
            Next.js!
          </a>
        </h1>

        <div className='grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3'>
          <CatCard {...base} />
          <CatCard {...base} />
          <CatCard {...base} />
        </div>
      </main>

      <footer className='mt-4'>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          className='text-blue-500 hover:underline'
        >
          Powered by Vercel
        </a>
      </footer>
    </div>
  );
}
